listen 443 ssl; # Listen on HTTPS port 443
listen [::]:443 ssl; # Listen on IPv6 for port 443

# Always block access to potentially sensitive files
location ~* \.(env|php)$ {
    deny all;
    # turn off logging to avoid clutter
    access_log off;
    log_not_found off;
}
