ssl_certificate /etc/ssl/pegasib.dev.bundle.pem;
ssl_certificate_key /etc/ssl/pegasib.dev.key;

# For Authenticated Origin Pulls
ssl_verify_client on;
ssl_client_certificate /etc/ssl/certs/cloudflare_authenticated_origin_pull_ca.crt;
