server {
    listen 51;
    server_name 51.pegasib.dev;

    include includes/blocking.conf;

    location / {
        proxy_pass http://localhost:8000; # Forward requests to Deno server on localhost port 8000
        include includes/proxy-headers.conf;
    }
}

server {
    listen 51;
    server_name kpop-heardle.pegasib.dev;

    include includes/blocking.conf;

    location / {
        proxy_pass http://localhost:9989;
        include includes/proxy-headers.conf;
    }
}

server {
    listen 51;
    server_name loona-heardle.pegasib.dev;

    return 301 $scheme://kpop-heardle.pegasib.dev$request_uri;
}
