// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_todays_song from "./routes/api/todays-song.ts";
import * as $index from "./routes/index.tsx";
import * as $guess_bar from "./islands/guess-bar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/todays-song.ts": $api_todays_song,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/guess-bar.tsx": $guess_bar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
