// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $links_middleware from "./routes/links/_middleware.ts";
import * as $links_github from "./routes/links/github.ts";
import * as $links_linkedin from "./routes/links/linkedin.ts";
import * as $links_wikipedia from "./routes/links/wikipedia.ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/links/_middleware.ts": $links_middleware,
    "./routes/links/github.ts": $links_github,
    "./routes/links/linkedin.ts": $links_linkedin,
    "./routes/links/wikipedia.ts": $links_wikipedia,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
